#!/bin/bash
#
# override variables
# DOCKER_REGISTRY : ghcr.io
# DOCKER_REGISTRY_USERNAME : username
# DOCKER_REGISTRY_TOKEN : token
# DOCKER_REPOSITORY : image repository path (default to lowercase(GITHUB_REPOSITORY))

set -e -o pipefail
set -x

DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME:? DOCKER_REGISTRY_USERNAME not defined}
DOCKER_REGISTRY_TOKEN=${DOCKER_REGISTRY_TOKEN:? DOCKER_REGISTRY_TOKEN not defined}

# default to ghcr.io
DOCKER_REGISTRY=${DOCKER_REGISTRY:-ghcr.io}
# default to lowercase(GITHUB_REPOSITORY)
[ -z "$DOCKER_REPOSITORY" ] && DOCKER_REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

export DOCKER_REPOSITORY DOCKER_REGISTRY DOCKER_REGISTRY_TOKEN DOCKER_REGISTRY_USERNAME

echo "$DOCKER_REGISTRY_TOKEN" | docker login ${DOCKER_REGISTRY} -u ${DOCKER_REGISTRY_USERNAME}  --password-stdin

make push-image DOCKER_REGISTRY=${DOCKER_REGISTRY} DOCKER_REPOSITORY=${DOCKER_REPOSITORY}

docker logout ${DOCKER_REGISTRY}

